---
name: CI Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup gitconfig
        run: |
          git config user.name 'autonomous-bot'
          git config user.email 'an.autonomous.bot@gmail.com'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Bump version
        run: |
          poetry run version info
          if [ "${GITHUB_REF##*/}" == "master" ]; then
            poetry run version bump --commit --tag
            poetry run version push
          else
            poetry run version bump
          fi
          poetry run version info --filepaths | tar -cvzf versioning.tar.gz -T -
      - name: Store versioned files
        uses: actions/upload-artifact@v3
        with:
          name: "versioning-${{ github.run_number }}"
          path: versioning.tar.gz
      # - name: Cache version changes
      #   id: versioned-files
      #   uses: actions/cache@v3
      #   with:
      #     key: "${{ runner.os }}-versioning-${{ hashFiles('versioning.tar.gz') }}"
      #     path: versioning.tar.gz
  #   outputs:
  #     version: "${{ steps.version.info }}"
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Lint
        run: |
          poetry run workflow-tools style.sort-headers.run --check
          poetry run workflow-tools style.format.run --check
          poetry run workflow-tools sca.lint.run
      - name: Type checking
        run: poetry run workflow-tools sca.type-checking.run
      # - name: Perform security checks
      #   run: |
      #     poetry run workflow-tools sec.sast.run
      #     poetry run workflow-tools sec.dependency-scan.run
  build:
    runs-on: ubuntu-latest
    needs: [version, sca]
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          python -m pip install poetry
          poetry install --no-dev
      - name: Download versioned files
        uses: actions/download-artifact@v3
        with:
          name: "versioning-${{ github.run_number }}"
      # - name: Overlay versioned files
      #   if: steps.versioned-files.outputs.cache-hit == 'true'
      - name: Perform build
        run: |
          tar -tvf versioning.tar.gz
          tar -xzf versioning.tar.gz
          poetry run workflow-tools dist.package.build
      - name: Perform publish
        run: |
          poetry config repositories.test-pypi 'https://test.pypi.org/legacy/'
          poetry config pypi-token.test-pypi "${{ secrets.TESTPYPI_TOKEN }}"
          poetry run workflow-tools dist.package.publish --repository test-pypi
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ['3.7', '3.8', '3.9', '3.10']
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: "Set up Python 3.10"
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.10
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install poetry
  #     - name: Install package fro test-pypi
  #       run: python3 -m pip install --index-url https://test.pypi.org/simple/
  #     # - name: Perform tests
  #     #   run: poetry run workflow-tools qa.unit-test.run
